/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PantsRouteImport } from './routes/pants'
import { Route as ShirtsRouteImport } from './routes/shirts'
import { Route as ShopRouteImport } from './routes/shop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PantsRoute = PantsRouteImport.update({
  id: '/pants',
  path: '/pants',
  getParentRoute: () => rootRouteImport,
} as any)
const ShirtsRoute = ShirtsRouteImport.update({
  id: '/shirts',
  path: '/shirts',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pants': typeof PantsRoute
  '/shirts': typeof ShirtsRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pants': typeof PantsRoute
  '/shirts': typeof ShirtsRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pants': typeof PantsRoute
  '/shirts': typeof ShirtsRoute
  '/shop': typeof ShopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pants' | '/shirts' | '/shop'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pants' | '/shirts' | '/shop'
  id: '__root__' | '/' | '/pants' | '/shirts' | '/shop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PantsRoute: typeof PantsRoute
  ShirtsRoute: typeof ShirtsRoute
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pants': {
      id: '/pants'
      path: '/pants'
      fullPath: '/pants'
      preLoaderRoute: typeof PantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shirts': {
      id: '/shirts'
      path: '/shirts'
      fullPath: '/shirts'
      preLoaderRoute: typeof ShirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PantsRoute: PantsRoute,
  ShirtsRoute: ShirtsRoute,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
